export const parcelTypes = {
  
  FETCH_PARCELS: "FETCH_PARCELS",
  CREATE_PARCEL: "CREATE_PARCEL",
  GET_PARCELS: "GET_PARCELS",
  SELECT_PARCEL: "SELECT_PARCEL",
  DELETE_PARCEL: "DELETE_PARCEL",
  UPDATE_PARCEL: "UPDATE_PARCEL",
};
