export const userTypes = { 
  CREATE_USER: "CREATE_USER",
  GET_USERS: "GET_USERS",
  SELECT_USER: "SELECT_USER",
  DELETE_USER: "DELETE_USER",
  UPDATE_USER: "UPDATE_USER",
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER"
  
};
